[
  "Acquire the Aged One Exultation Talisman",
  "Acquire the Perfumed Oil of Ranah",
  "Kill a boss after inflicting 3 different status effects",
  "Kill Queelign in Belurat",
  "Kill a Remembrance boss with a remembrance weapon",
  "Collect 4 perfumer bottles",
  "Acquire ${rand([3,4,5])} Spirit Ashes",
  "Clear 2 Forges",
  "Acquire Verdigris Discus",
  "Burn the Sealing tree",
  "Kill a boss with Backhand Blades only",
  "Acquire Full Gravebird armor set",
  "Complete two nameless mauseloums",
  "Give an Iris of Grace",
  "Clear 2 Gaols",
  "Kill ${rand([3,4,5])} Ulcerated Tree Spirits",
  "Kill Senessax",
  "Acquire ${rand([3,4,5])} Larval Tears",
  "Kill Rellana",
  "Kill the Deathrite Bird",
  "Kill ${rand([3,4,5])} Remembrance bosses",
  "Kill Gaius",
  "Kill Midra",
  "Drink Thiollier's Concoction",
  "Acquire Devonia's hammer",
  "Kill Scadutree Avatar",
  "Acquire Death Mask Helm, Winged Seprent Helm and Salza's Hood",
  "Acquire Commander Gaius pants",
  "Kill Putrescent Knight",
  "Give an Iris of Occultation",
  "Kill Leda and her companions",
  "Acquire both Aspect of the Crucible Incantations",
  "Acquire ${rand([4,5,6])} talismans",
  "Kill a boss with hand to hand only",
  "Kill a base game boss in DLC",
  "Acquire Jolan and Ana summon",
  "Kill the Tree Sentinel duo",
  "Kill a boss on heavy load",
  "Kill a boss with a +0 weapon",
  "Acquire the Scorpion Stew",
  "Acquire ${rand([4,5,6,7,8])} sorceries",
  "Kill a Golden Hippo",
  "Kill a Black Knight boss",
  "Kill a Red Bear",
  "Acquire the Golden Braid",
  "Acquire ${rand([3,4,5])} Hefty Pots",
  "Use a Transformation",
  "Kill a boss using perfume bottles only",
  "Acquire ${rand([5,6,7])} incantations",
  "Sell Bloodfiends arm +0",
  "Kill Ancient Dragon Man boss",
  "Visit ${rand([4,5,6])} Miquella crosses",
  "Kill ${rand([2,3,4])} unique curseblade assassins",
  "Kill Bols infront of Castle Ensis",
  "Acquire ${rand([3,4,5])} NPC weapons",
  "Kill Moonrithyll",
  "Kill ${rand([3,4,5])} Dragon Bosses",
  "Reach level ${rand([8,9,10,11,12])} Scadu",
  "Drain the water in the church",
  "Memory of Grace with 600k runes",
  "Acquire a Leda Rune",
  "Kill Bayle while summoning Igon",
  "Kill Mesmer",
  "Kill Jori",
  "Acquire Sword of Light/Darkness",
  "Acquire Velvet St.Trina Sword",
  "Acquire Level 5 Revered Spirit Ash",
  "Acquire ${rand([2,3,4])} Kindred Cookbooks",
  "Kill Dryleaf Dane in a duel",
  "Dupe a Remembrance",
  "Acquire Euporia",
  "Kill a Dancing Lion",
  "Kill Consort Radahn",
  "Kill Lamenter Boss",
  "Kill ${rand([3,4,5])} NPC bosses",
  "Acquire ${rand([2,3,4])} hanging pot bell bearings",
  "Kill a Remembrance boss hitless",
  "Heal the wounded Kindred rot",
  "Kill Count Ymir",
  "Kill the Rolling Giant Lightning Ram",
  "Kill a boss consumables only",
  "Have St.Trina talk to you",
  "Kill ${rand([2,3])} unique NPC invaders",
  "Acquire Taylew, Golem Smith",
  "Upgrade a Remembrance weapon to max",
  "Kill a bear/hippo/lion",
  "Kill a Death Knight",
  "Clear ${rand([1,2])} catacombs",
  "Acquire Moore armor set",
  "Acquire ${rand([2,3,4])} painting rewards",
  "Acquire ${rand([2,3,4])} blessings of Marika",
  "Kill a Furnace Golem",
  "Kill ${rand([2,3,4])} Hippos",
  "Put Florissax to sleep",
  "Acquire ${rand([3,4,5])} Ashes of War",
  "Acquire ${rand([2,3,4])} Dragon Hearts",
  "Kill a Remembrance boss after 6 parries",
  "Have bloodsucking tear drain your max hp",
  "Collect 2 full armor sets",
  "Acquire a legendary ash summon",
  "Acquire Igon's Furled Finger",
  "Kill Metyr",
  "Kill Romina",
  "Kill all sleeping animals in Stone Coffin Fissure",
  "Kill Demihuman Marigga",
  "Kill a Remembrance boss at 0 Scadu",
  "Kill ${rand([3,4,5])} bosses that have a Zoo animal in their name",
  "Acquire ${rand(['a','all'])} torch",
  "Kill Logar",
  "Kill Giant Hand in Dheo Ruins",
  "Kill The Frenzy NPC",
  "Acquire ${rand([3,4,5])} NPC dropped weapons",
  "Kill Chief Bloodfiend",
  "Kill a Demihuman Swordsman",
  "Sell Great Katana at +0",
  "Acquire 3 shields",
  "Kill all 3 Divine Beast Warriors in Enir Ilim",
  "Acquire Tibia Cookbook",
  "Kill a boss sorcery only",
  "Acquire the torn diary page",
  "Kill a Remembrance boss using Colossal weapons only",
  "Kill Deatblighting Dancing Lion",
  "Break Miquellas charm using Miquella's great rune",
  "Acquire Talisman of all Crucibles",
  "Kill a boss incantations only",
  "Deliver Secret Rite Scroll to Ansbach",
  "Kill Rakshasa"
]
